### ISSUE TITLE
Working with Node 0.8.7

### ISSUE THREAD

**Issue by jtomasrl** [technosophos/Pronto.js#1]
will pronto.js work with Node.js 0.8.7 and further versions?

**Comment by technosophos** [comment]
To my knowledge it should. Because of the projects I've been working on, I've been sticking to the 0.6 releases, but I've been watching the 0.8 branch and haven't seen anything that makes me think it would not work there.

If you happen to find anything broken, please let me know. I'm doing active work with Pronto, so I am in the code just about every day. But I'm trying to restrain myself to only fixing bugs until I have a few other projects wrapper up and released.

**Comment by technosophos** [comment]
I got a GitHub email about this issue, but I don't see any update to this ticket. Did you get things resolved?

I'm allocating some time to updating the docs and stuff over the next few weeks. Let me know if there is anything in particular that you feel needs some clarification.

**Comment by jtomasrl** [comment]
indeed it worked over node.js 0.8.8, same with pronto-mongoDB driver

**Comment by technosophos** [comment]
Okay. Marking this as closed.
